name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Android
      run: |
        cd ../PolyNavi/PolyNavi
        nuget restore
        cd Polynavi.Droid
        msbuild Polynavi.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~Bll|FullyQualifiedName~Dal"
