name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd Polynavi.Droid
        msbuild Polynavi.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~Bll|FullyQualifiedName~Dal"
